#Default Animal Protect Config
notify: true
shear-protect: true
debug: false
protect-from-player:
     - CHICKEN
     - COW
     - MUSHROOM_COW
     - OCELOT
     - PIG
     - SHEEP
     - WOLF
     - IRON_GOLOM
     - SNOWMAN
     - HORSE
protect-from-monsters:
     - VILLAGER
NoDamagePermMsg: Du kannst hier keine Tiere angreifen!
NoRideBecauseNoBuildPermMsg: Du darfst in diesem Gebiet kein Reittier benutzen!
NoRideBecauseNotOwnerMsg: Du hast keine Erlaubnis fuer dieses Reittier!
MountOwnerMsg: Dieses Reittier gehoert
CommandFail: Du hast keine Rechte um das zu tun!
AdminNotification: hat versucht ein geschuetztes Tier zu toeten.
