name: AnimalProtect
version: 1.5.1b
authors: [damo1995, CubieX]
main: me.damo1995.AnimalProtect.AnimalProtect
depend: [WorldGuard]

commands:
  animalprotect:
    description: 'General AnimalProtect Commands'
    usage: /animalprotect version|reload|list
    aliases: ap

permissions:
  animalprotect.admin:
    description: admin permission node
    children:
      animalprotect.notify: true
      animalprotect.bypass: true
      animalprotect.list: true
    default: op
  animalprotect.notify:
    description: notify permission node
    default: op
  animalprotect.bypass:
    description: bypass animalprotection.
    default: op
  animalprotect.list:
    description: List the configuration options.
    default: op
